import type { GrantPool } from './types'

/**
 * Seed data for when no switchboard is reachable. Lets reviewers explore
 * the experience without running `ph switchboard` locally. Dropped the
 * moment any GraphQL endpoint responds.
 *
 * Shape matches rfp-hub-app/document-models/grant-pool GrantPoolState.
 */
export const SAMPLE_POOLS: GrantPool[] = [
  {
    id: 'sample-ef-rfp-hub',
    createdAt: '2026-02-23T00:00:00Z',
    updatedAt: '2026-04-22T00:00:00Z',
    grantSystemRef: 'sample-system-ef',
    name: 'Standard RFP Object and Public Aggregation API',
    description:
      'Build an open, neutral aggregation platform that consolidates fragmented funding opportunities across web3 into a single, accessible resource. Versioned RFP object, public API with search/filter/pagination, duplicate detection, community submissions with governance review, verified publishers.',
    grantFundingMechanism: 'REQUEST_FOR_PROPOSAL',
    isOpen: true,
    openDate: '2026-02-23T00:00:00Z',
    closeDate: '2026-04-23T23:59:59Z',
    applicationsURI: 'https://esp.ethereum.foundation/applicants/rfp/rfp_hub',
    governanceURI: 'https://esp.ethereum.foundation',
    attestationIssuersURI: null,
    requiredCredentials: [],
    totalGrantPoolSize: [],
    totalGrantPoolSizeInUSD: null,
    minGrant: [],
    maxGrant: [],
    email: 'esp@ethereum.org',
    image: null,
    coverImage: null,
    extensions: null,
    sameAs: ['https://esp.ethereum.foundation/applicants/rfp/rfp_hub'],
    code: 'ESP-RFP-HUB-2026',
    briefingURI: 'https://esp.ethereum.foundation/applicants/rfp/rfp_hub',
    eligibilityCriteria:
      'Open to any team with production experience in ecosystem infrastructure. AGPL-3.0 code and CC0 schema encouraged.',
    evaluationCriteria:
      'Standards alignment (DAOIP-5, schema.org/Grant). Architectural differentiators for non-discriminatory operation. Publisher commitments.',
    contextDocuments: [],
    reviewers: [],
    categories: ['Infrastructure', 'Funding', 'Open Standards'],
    ecosystems: ['Ethereum'],
    tags: ['aggregator', 'daoip-5', 'public-goods'],
    lifecycle: 'OPEN',
    submitter: {
      type: 'VERIFIED_PUBLISHER',
      identifier: 'did:ethr:ethereum-foundation',
      submittedAt: '2026-02-23T00:00:00Z',
    },
    publisher: {
      identifier: 'did:ethr:ethereum-foundation',
      publishedAt: '2026-02-23T00:00:00Z',
    },
    lastVerifiedAt: '2026-02-23T00:00:00Z',
    verificationMethod: 'DOMAIN_VERIFICATION',
    verifiedBy: 'ethereum.foundation',
    governanceState: 'APPROVED',
    supersedes: null,
    claimedFromEntry: null,
    duplicateOf: null,
  },
  {
    id: 'sample-optimism-retro',
    createdAt: '2026-03-01T00:00:00Z',
    updatedAt: '2026-03-01T00:00:00Z',
    grantSystemRef: 'sample-system-optimism',
    name: 'Optimism Retro Funding · Round 5',
    description:
      'Retroactive funding for public goods that have measurably improved the Optimism / Superchain ecosystem over the last year.',
    grantFundingMechanism: 'RETRO_FUNDING',
    isOpen: false,
    openDate: '2026-05-01T00:00:00Z',
    closeDate: '2026-05-15T23:59:59Z',
    applicationsURI: 'https://atlas.optimism.io/rounds/retro-5',
    governanceURI: null,
    attestationIssuersURI: null,
    requiredCredentials: [],
    totalGrantPoolSize: [{ id: 'op-pool-1', amount: '10000000' }],
    totalGrantPoolSizeInUSD: '22000000',
    minGrant: [{ id: 'op-min-1', amount: '1000' }],
    maxGrant: [{ id: 'op-max-1', amount: '500000' }],
    email: null,
    image: null,
    coverImage: null,
    extensions: null,
    sameAs: [],
    code: 'OP-RETRO-5',
    briefingURI: null,
    eligibilityCriteria: null,
    evaluationCriteria: null,
    contextDocuments: [],
    reviewers: [],
    categories: ['Retroactive Funding', 'Public Goods'],
    ecosystems: ['Optimism', 'Superchain'],
    tags: ['retro', 'op'],
    lifecycle: 'UPCOMING',
    submitter: {
      type: 'VERIFIED_PUBLISHER',
      identifier: 'did:ethr:optimism',
      submittedAt: '2026-03-01T00:00:00Z',
    },
    publisher: {
      identifier: 'did:ethr:optimism',
      publishedAt: '2026-03-01T00:00:00Z',
    },
    lastVerifiedAt: '2026-03-01T00:00:00Z',
    verificationMethod: 'DOMAIN_VERIFICATION',
    verifiedBy: 'optimism.io',
    governanceState: 'APPROVED',
    supersedes: null,
    claimedFromEntry: null,
    duplicateOf: null,
  },
  {
    id: 'sample-gitcoin-grants',
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-04-01T00:00:00Z',
    grantSystemRef: 'sample-system-gitcoin',
    name: 'Gitcoin Grants · Round 25',
    description:
      'Quadratic-funded grants round supporting open source and public-goods projects across web3.',
    grantFundingMechanism: 'QUADRATIC_FUNDING',
    isOpen: true,
    openDate: '2026-04-10T00:00:00Z',
    closeDate: '2026-05-01T23:59:59Z',
    applicationsURI: 'https://grants.gitcoin.co/round-25',
    governanceURI: null,
    attestationIssuersURI: null,
    requiredCredentials: ['gitcoin-passport'],
    totalGrantPoolSize: [{ id: 'gc-pool-1', amount: '1500000' }],
    totalGrantPoolSizeInUSD: '1500000',
    minGrant: [],
    maxGrant: [],
    email: null,
    image: null,
    coverImage: null,
    extensions: null,
    sameAs: [],
    code: 'GC-R25',
    briefingURI: null,
    eligibilityCriteria: 'Gitcoin Passport score >= 20.',
    evaluationCriteria: 'Community-curated via quadratic matching.',
    contextDocuments: [],
    reviewers: [],
    categories: ['Quadratic Funding', 'Open Source'],
    ecosystems: ['Ethereum'],
    tags: ['qf', 'gitcoin'],
    lifecycle: 'OPEN',
    submitter: {
      type: 'COMMUNITY',
      identifier: 'did:ethr:0x1234…abcd',
      submittedAt: '2026-04-01T00:00:00Z',
    },
    publisher: {
      identifier: 'did:ethr:gitcoin',
      publishedAt: '2026-04-01T00:00:00Z',
    },
    lastVerifiedAt: '2026-04-01T00:00:00Z',
    verificationMethod: 'REVIEWER_CONFIRMATION',
    verifiedBy: 'reviewer-1',
    governanceState: 'APPROVED',
    supersedes: null,
    claimedFromEntry: null,
    duplicateOf: null,
  },
]
